version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: app
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html
    networks:
      - laravel
    depends_on:
      - db
      - node # Node.jsの依存関係を追加

  webserver:
    image: nginx:alpine
    platform: linux/amd64
    container_name: webserver
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel
    depends_on:
      - app

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: node
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html
    networks:
      - laravel

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge